### ISSUE TITLE
Hey where is your smaple paper written in groff ms?

### ISSUE THREAD

**Issue by SymphonySimper** [SudarsonNantha/LinuxConfigs#1]
This one
https://www.reddit.com/r/groff/comments/mp0sin/i_made_an_example_of_a_scientific_paper_using/

**Comment by SudarsonNantha** [comment]
Hey thanks for bringing this up. I moved some things around and accidentally removed those files.
They should be back up now.

**Comment by SymphonySimper** [comment]
Thanks a lot!
